#backend
version:  '3.8'

services: 
  frontendimg:  
    build:  /root/studentapp-3tire-dockerimage/frontend
    container_name: frontend
    network_mode:  bridge
    ports: 
      - 80:80
    img:
    build:  /root/studentapp-3tire-dockerimage/backend
    container_name : backend
    network_mode:  bridge
    ports: 
      - 8080:8080
    depends_on:
      - frontend
    
